### ISSUE TITLE
Feature request: Add node status indication

### ISSUE THREAD

**Issue by ardevd** [lncapital/torq#71] opened 2022-09-19 18:23 UTC
Currently, the UI doesn't seem to indicate whether the stored node details are valid or not (ie: can Torq actually communicate with the GRPC service for the specified node). Would be useful to get some sort of feedback on whether Torq can connect to a given node. There is a green "play" icon displayed which one would think actually indicates node connection status, but that seems to just be a static hard coded image.

**Comment by maxwedwards** [comment] 2022-09-21 17:35
Agree with this feature request. We have recently refactored the connection code to make it easier to show the connection status on the frontend but I have no ETA on adding this last step as we are trying to get some other features we consider more important in first.

**Comment by ohenrik** [comment] 2022-10-02 18:58
Duplicate of #103 

Thank you for the feature request, I just noticed that I created a duplicate issue, but since it has more context I'm closing this.

**Closed by ohenrik** 2022-10-02 18:58 UTC
Labels: feature
