### ISSUE TITLE
Bug: When the node is not reachable anymore perform a simple healthcheck test.

### ISSUE THREAD

**Issue by 2Fast2BCn** [lncapital/torq#93] opened 2022-09-23 20:12 UTC
Right now when torq loses connectivity to LND I see 24 concurrent attempts to obtain data every few seconds maybe when we lost connectivity we can do just one healthcheck test every few seconds instead.

**Comment by ohenrik** [comment] 2022-10-06 15:06
Duplicate of #103

**Closed** 2022-10-06 15:07 UTC
Labels: bug
